In [2]:
import numpy as np

In [3]:
numbers = [1,2,3,4,5,6,7,8,9,10]
nums = [10,9,8,7,6,5,4,3,2,1]
add1 = numbers + nums
print(add1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [4]:
# array function
nums_array = np.array(nums)
nums_array

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [5]:
numbers_array = np.array(numbers)
numbers_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
add2 = nums_array+numbers_array
add2


array([11, 11, 11, 11, 11, 11, 11, 11, 11, 11])

# WITH ARRAYS
- It adds element wise 

In [7]:
# mean - with numpy
numbers_array.mean()

np.float64(5.5)

In [8]:
numbers_array.sum()

np.int64(55)

In [ ]:
# standard deviation
numbers_array.std()

np.float64(2.8722813232690143)

In [11]:
# variance
numbers_array.var()

np.float64(8.25)